# Generated by Django 3.0.5 on 2020-04-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=63, unique=True, verbose_name='Artist Name')),
                ('artist_genre', models.CharField(choices=[('BalRnB', 'Ballad/RnB'), ('Dance', 'Dance'), ('RockInd', 'Rock/Indie'), ('HipElec', 'Hiphop/Elec'), ('Others', 'Jazz/Trot/Folk'), ('Foreign', 'Foreign')], max_length=15, null=True, verbose_name='Artist Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_source', models.CharField(choices=[('Inpark', 'Interpark'), ('Melon', 'Melon'), ('Yes24', 'Yes24'), ('Link', 'Ticketlink'), ('Auction', 'Auction'), ('Hana', 'Hanaticket')], max_length=15, verbose_name='Info Source Site')),
                ('detail_url', models.CharField(max_length=255, verbose_name='Detail Page URL')),
                ('concert_name', models.CharField(max_length=127, unique=True, verbose_name='Concert Name')),
                ('location', models.CharField(max_length=31, verbose_name='Concert Location')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Concert Location Address')),
                ('start_date', models.DateField(verbose_name='Concert Starting Date')),
                ('end_date', models.DateField(verbose_name='Concert Ending Date')),
                ('is_opened', models.BooleanField(verbose_name='Is Ticket Opened?')),
                ('open_time', models.DateTimeField(null=True, verbose_name='Ticket Opening Time')),
                ('artists', models.ManyToManyField(null=True, to='concert.Artist', verbose_name='Artists in Concert')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(max_length=31, unique=True, verbose_name='Price Type')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.Concert', verbose_name='Concert')),
            ],
        ),
    ]
