# Generated by Django 3.0.5 on 2020-04-20 12:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BalRnB', 'Ballad/RnB'), ('Dance', 'Dance'), ('RockInd', 'Rock/Indie'), ('HipElec', 'Hiphop/Elec'), ('Others', 'Jazz/Trot/Folk'), ('Foreign', 'Foreign')], max_length=43, null=True, verbose_name='User Preffered Genres'),
        ),
    ]
